config/routes.rb
# Version: $Id$
#
#

# Commentary:
#
#

# Change Log:
#
#

# Code:

DtkWww::Application.routes.draw do

  get "home/index"

  ## #################################################################
  ##
  ## #################################################################

  get "plugins", to: 'plugin#index'
  get "plugin/:id", to: 'plugin#show'

  ## #################################################################
  ##
  ## #################################################################

  get "code",             to: 'code#index'

  ## #################################################################
  ##
  ## #################################################################

  get "docs",             to: 'docs#index', as: 'docs'
  get "doc/:layer/:path", to: 'docs#show',  as: 'doc'

  ## #################################################################
  ##
  ## #################################################################

  devise_for :users

  ## #################################################################
  ##
  ## #################################################################

  root 'home#index'
end

#
# routes.rb ends here

app/views/layouts/_footer.html.erb
<footer>

</footer>

app/views/layouts/_header.html.erb
<header>

</header>

app/views/layouts/_main.html.erb
<main class="container-fluid">

  <% if flash[:notice] %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= notice %>
  </div>
  <% end %>

  <% if flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= alert %>
  </div>
  <% end %>

  <%= yield %>
</main>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">dtk</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>">Home</a></li>
        <li><a href="/doc/dtkdoc/index.html">Docs</a></li>
        <li><a href="<%= code_path %>">Code</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
        <li><a href="<%= new_user_session_path %>">Sign in</a></li>
        <% else %>
        <li><a href="<%= destroy_user_session_path %>" data-method="delete">Sign out</a></li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
         <img src="http://www.gravatar.com/avatar/<%= Digest::MD5.hexdigest(current_user.email) %>" class="nav navbar-nav navbar-right navbar-text "/>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>dtk</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/styles/qtcreator_light.min.css">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/header' %>
    <%= render 'layouts/main' %>
    <%= render 'layouts/footer' %>
  </body>

  <script>
    $(document).ready(function() {
      $('pre').each(function(i, block) {
        hljs.highlightBlock(block);
      });
    });
  </script>
</html>